preserve_hierarchy: true

files:
  - source: /locales/en/**/*.json

    translation: /locales/%two_letters_code%/**/%original_file_name%

    languages_mapping:
      two_letters_code:
        en: en
